version: '3.4'
services:

  scholarship.api.users:
    image: ${DOCKER_REGISTRY-}scholarshipapiusers
    build:
      context: .
      dockerfile: Scholarship.Systems/Scholarship.Api.Users/Dockerfile

  scholarship.api.loans:
    image: ${DOCKER_REGISTRY-}scholarshipapiloans
    build:
      context: .
      dockerfile: Scholarship.Systems/Scholarship.Api.Loans/Dockerfile


  scholarship.gateway:
    image: ${DOCKER_REGISTRY-}scholarshipgateway
    build:
      context: .
      dockerfile: Scholarship.Systems/Scholarship.Gateway/Dockerfile

  scholarship.api.backup:
    image: ${DOCKER_REGISTRY-}scholarshipapibackup
    build:
      context: .
      dockerfile: Scholarship.Systems/Scholarship.Api.Backup/Dockerfile


